### ISSUE TITLE
Bioferrite Harvester Constantly Desynchronizing

### ISSUE THREAD

**Issue by 1343008086** [rwmt/Multiplayer#466] opened 2024-05-15 06:39 UTC
Thank you for supporting the RimWorld multiplayer mod. Here are some issues I encountered during gameplay. I have categorized these desynchronization reports based on my judgment to help you review them more effectively.

[Bioferrite Harvester Constantly Desynchronizing.zip](https://github.com/rwmt/Multiplayer/files/15317256/Bioferrite.Harvester.Constantly.Desynchronizing.zip)

**Comment by ZombieProtectionAgency** [comment] 2024-05-17 12:17
@1343008086 The issues you are reporting are probably going to be helpful for the devs, though please keep in mind if you are seeing issues with common things, others probably are too. Before you submit issues, please give the issue list a review. This issue looks like it is a duplicate of an existing issue. #447

**Comment by SokyranTheDragon** [comment] 2024-07-06 20:32
Closing as it looks like it's a duplicate #447

**Closed by SokyranTheDragon** 2024-07-06 20:32 UTC
