### ISSUE TITLE
Desync when trying to surround traders with walls

### ISSUE THREAD

**Issue by pavlukivan** [rwmt/Multiplayer#103] opened 2020-07-23 10:52 UTC
the title is self-explanatory, right? When surrounding traders with walls, a desync happens for all connected clients. It happened pretty consistently, I can submit a save if you want.

**Comment by Zetrith** [comment] 2020-07-24 14:02
Can't reproduce. Were you using any mods?

**Comment by notfood** [comment] 2020-07-24 16:51
[![](http://img.youtube.com/vi/PdqZcp_6QSg/0.jpg)](http://www.youtube.com/watch?v=PdqZcp_6QSg "Issue #103")

Can't reproduce, just arbiter alone works fine. Client to Client works fine too.

I suspect different configs.

**Comment by pavlukivan** [comment] 2020-07-27 07:10
@notfood please reopen, here's a save. It has more mods, but the desync happens even when having nothing except core, royalty, multiplayer and harmony

https://cdn.discordapp.com/attachments/699470828311674928/737205058328068147/pavlukivans_game.zip  
https://cdn.discordapp.com/attachments/699470828311674928/737205079567761469/Autosave-5.zip  
https://cdn.discordapp.com/attachments/699470828311674928/737205145649152051/Desync-24.zip

**Comment by notfood** [comment] 2020-07-27 10:55
You have 0 score mods in your list. Better Pawn Control is a suspect.

If you want to report a vanilla issue, bring a vanilla save.

**Comment by pavlukivan** [comment] 2020-07-27 13:02
As I mentioned, it also works with all mods except multiplayer disabled

**Comment by Zetrith** [comment] 2020-07-27 15:49
I loaded the save and walled the traders in until they tried to break out. No desync happened both with arbiter and another client. If you can, please provide consistent reproduction steps in vanilla.

**Comment by pavlukivan** [comment] 2020-07-27 18:23
desync happens almost immediately for me at that save after finishing constructing the wall above the door

**Comment by Zetrith** [comment] 2020-07-27 21:34
Thanks a lot for the video. Apparently it's a UI side-effect related to prioritized work. Looks like your save has just the right conditions (async time etc). Will get fixed in the next version.

**Closed by Zetrith** 2020-07-27 21:34 UTC
Labels: can't reproduce, desync
