### ISSUE TITLE
The needs window is not displayed

### ISSUE THREAD

**Issue by xeynyty** [rwmt/Multiplayer#336] opened 2022-11-06 13:45 UTC
### **The needs window is not displayed in Rimworld 1.4.3523 and Multiplayer v0.7**
<img width="650" alt="image" src="https://user-images.githubusercontent.com/50880754/200174381-5ff11517-fe56-4070-8553-2ef5fd8ff79d.png">

**Comment by SokyranTheDragon** [comment] 2022-11-11 18:31
Current version is 1.4.3542, so you're using an outdated RimWorld, closing the issue due to that. We can reopen this if you can reproduce it on the most recent version of the game.

**Comment by SokyranTheDragon** [comment] 2022-11-11 18:32
And if you're able to reproduce it on the most recent version of the game, then include the log file. We can't help out without it.

**Closed by SokyranTheDragon** 2022-11-11 18:31 UTC
Labels: bug, invalid, 1.4

**Comment by mmatotan** [comment] 2022-11-13 13:19
Updating the game solved this issue, thanks!
