### ISSUE TITLE
Unable to select\deselect pawns as target in ritual spot.

### ISSUE THREAD

**Issue by qDshun** [rwmt/Multiplayer#458] opened 2024-05-05 23:29 UTC
Multiplayer 0.10.2
RimWorld 1.5.4085

Plus, Ritual always applies (example: role change) to the first pawn in the UI in the top of the screen instead of the one it should

**Comment by SokyranTheDragon** [comment] 2024-05-06 15:23
Rituals being broken is a duplicate of #429

**Closed by SokyranTheDragon** 2024-05-06 15:23 UTC
Labels: bug, 1.5
